import type { ModuleRule } from './types';

const WIN_GRADES = [
  { key: 'first', label: '第一等次（一等）' },
  { key: 'second', label: '第二等次（二等）' },
  { key: 'third', label: '第三等次（三等）' },
  { key: 'participation', label: '参与/未获奖' },
];

export const MODULE_RULES: ModuleRule[] = [
  {
    id: 'social-practice',
    index: '01',
    name: '社会实践',
    description: '学校、学院统一安排的寒暑期社会实践活动。',
    cap: 8,
    teamHalved: false,
    dedup: 'term',
    scoring: 'option',
    needsTerm: true,
    namePlaceholder: '如：三下乡·乡村振兴调研实践队',
    options: [
      { key: 'national-team', label: '国家级重点团队', points: 4 },
      { key: 'provincial-team', label: '省级重点团队', points: 4 },
      { key: 'school-team', label: '校级团队', points: 3 },
      { key: 'college-team', label: '院级团队', points: 2 },
    ],
    ruleNotes: [
      '一个假期原则上只记一次社会实践，同期多条记录按最高档计分。',
      '需填写所属假期（如「2025 暑假」），并上传实践证明（线下审核）。',
    ],
  },
  {
    id: 'volunteer',
    index: '02',
    name: '志愿服务',
    description: '学校、学院统一安排的志愿服务，以志愿者联合会记录时长或提供的证明认定。',
    cap: 10,
    teamHalved: false,
    dedup: 'none',
    scoring: 'hours',
    perHour: 0.2,
    needsHours: true,
    namePlaceholder: '如：迎新志愿服务',
    options: [
      { key: 'united-federation', label: '校志愿者联合会认证活动', points: 0 },
      { key: 'school-organized', label: '学校统一组织活动', points: 0 },
      { key: 'college-organized', label: '学院统一组织活动', points: 0 },
    ],
    ruleNotes: [
      '不含专业实习实践、课堂教学安排的课外实践和作业性质的实践。',
      '每 1 小时计 0.2 分，以证明材料认定的累计时长为准。',
    ],
  },
  {
    id: 'honor',
    index: '03',
    name: '各级表彰',
    description: '个人或团体获得的国家级、省级、地市级、校级、学院级荣誉成果。',
    cap: 10,
    teamHalved: true,
    dedup: 'name',
    scoring: 'option',
    namePlaceholder: '如：山东省优秀学生干部',
    options: [
      { key: 'national', label: '国家级荣誉', points: 10 },
      { key: 'provincial', label: '省级荣誉', points: 7 },
      { key: 'municipal', label: '地市级荣誉', points: 5 },
      { key: 'school', label: '校级荣誉', points: 3 },
      { key: 'college', label: '学院级荣誉', points: 1.5 },
    ],
    ruleNotes: [
      '不含各类奖学金、荣誉称号。',
      '因同一事项获多个层级荣誉的，不累计加分，按最高层级计分。',
      '团队荣誉个人加分减半。',
    ],
  },
  {
    id: 'research',
    index: '04',
    name: '科研创作',
    description: '出版著作、学术论文、专利成果等科研创作类成果。',
    cap: 15,
    teamHalved: false,
    dedup: 'name',
    scoring: 'option',
    namePlaceholder: '如：《乡村振兴视角下的……》（著作/论文/专利名称）',
    options: [
      { key: 'book-national-first', label: '出版著作·国家级出版社·独著/第一作者', points: 15, group: 'book' },
      { key: 'book-national-coauthor', label: '出版著作·国家级出版社·合著', points: 9, group: 'book' },
      { key: 'book-national-participant', label: '出版著作·国家级出版社·参与编写', points: 6, group: 'book' },
      { key: 'book-other-first', label: '出版著作·其他出版社·独著/第一作者', points: 12, group: 'book' },
      { key: 'book-other-coauthor', label: '出版著作·其他出版社·合著', points: 7, group: 'book' },
      { key: 'book-other-participant', label: '出版著作·其他出版社·参与编写', points: 5, group: 'book' },
      { key: 'paper-core-first', label: '学术论文·SCI/EI/核心期刊·第一作者', points: 12, group: 'paper' },
      { key: 'paper-core-other', label: '学术论文·SCI/EI/核心期刊·其他作者', points: 6, group: 'paper' },
      { key: 'paper-general-first', label: '学术论文·普通期刊·第一作者', points: 6, group: 'paper' },
      { key: 'paper-general-other', label: '学术论文·普通期刊·其他作者', points: 3, group: 'paper' },
      { key: 'patent-invention', label: '专利成果·发明专利', points: 10, group: 'patent' },
      { key: 'patent-utility', label: '专利成果·实用新型专利', points: 5, group: 'patent' },
      { key: 'patent-design', label: '专利成果·外观设计专利', points: 3, group: 'patent' },
    ],
    ruleNotes: [
      '著作需注明出版社与初版第一次印刷时间（即证书落款日期）。',
      '同一成果不重复计分，同名成果按最高档计。',
    ],
  },
  {
    id: 'culture-sports',
    index: '05',
    name: '文体活动',
    description: '文艺、体育类活动及比赛获奖。',
    cap: 10,
    teamHalved: true,
    dedup: 'none',
    scoring: 'matrix',
    namePlaceholder: '如：校运动会 4×100 米接力',
    matrix: {
      grades: WIN_GRADES,
      levels: [
        { key: 'national', label: '国家级', grades: { first: 10, second: 8, third: 6, participation: 2 } },
        { key: 'provincial', label: '省级', grades: { first: 7, second: 5.5, third: 4, participation: 1.2 } },
        { key: 'municipal', label: '地市级', grades: { first: 4.5, second: 3.5, third: 2.5, participation: 0.8 } },
        { key: 'school', label: '校级', grades: { first: 3, second: 2.2, third: 1.6, participation: 0.5 } },
        { key: 'college', label: '学院级', grades: { first: 1.5, second: 1, third: 0.7, participation: 0.3 } },
      ],
    },
    ruleNotes: ['团体项目个人加分减半。', '不同活动可累计加分，模块总分封顶 10 分。'],
  },
  {
    id: 'competition',
    index: '06',
    name: '学术竞赛',
    description: '学科竞赛，项目类别以《学生竞赛管理办法》为准。',
    cap: 15,
    teamHalved: true,
    dedup: 'name',
    scoring: 'matrix',
    namePlaceholder: '如：全国大学生数学建模竞赛',
    matrix: {
      grades: WIN_GRADES,
      levels: [
        { key: 'a', label: 'A 类（国家级重点竞赛）', grades: { first: 12, second: 9, third: 7, participation: 2 } },
        { key: 'b', label: 'B 类（省部级竞赛）', grades: { first: 7, second: 5, third: 3.5, participation: 1 } },
        { key: 'c', label: 'C 类（校级竞赛）', grades: { first: 3, second: 2, third: 1.2, participation: 0.5 } },
      ],
    },
    ruleNotes: [
      '获奖名称限 50 字以内，日期精准到日，指导老师可填多项（线下材料）。',
      '同一赛事获奖不累计，按最高等次计分。',
      '团体（组队）项目个人加分减半。',
    ],
  },
  {
    id: 'certificate',
    index: '07',
    name: '等级证书',
    description: '外语、计算机、普通话、教师资格等专业等级证书。',
    cap: 8,
    teamHalved: false,
    dedup: 'optionGroup',
    scoring: 'option',
    namePlaceholder: '如：大学英语六级（550 分）',
    options: [
      { key: 'cet6-high', label: '大学英语六级（≥500 分）', points: 5, group: 'cet' },
      { key: 'cet6', label: '大学英语六级（425–499 分）', points: 4, group: 'cet' },
      { key: 'cet4', label: '大学英语四级', points: 2.5, group: 'cet' },
      { key: 'ncre3', label: '全国计算机等级考试三级', points: 3, group: 'ncre' },
      { key: 'ncre2', label: '全国计算机等级考试二级', points: 2, group: 'ncre' },
      { key: 'putonghua-1a', label: '普通话水平测试一级甲等', points: 3, group: 'putonghua' },
      { key: 'putonghua-1b', label: '普通话水平测试一级乙等', points: 2.5, group: 'putonghua' },
      { key: 'putonghua-2a', label: '普通话水平测试二级甲等', points: 1.5, group: 'putonghua' },
      { key: 'teacher-cert', label: '教师资格证', points: 3, group: 'teacher' },
      { key: 'other-cert', label: '其他专业等级证书', points: 1.5, group: 'other' },
    ],
    ruleNotes: ['同类证书（同一证书组）只按最高档次计一次，不同类别证书可累计。'],
  },
  {
    id: 'publicity',
    index: '08',
    name: '宣传作品',
    description: '在各级媒体发表的文章、新闻稿等宣传作品。',
    cap: 6,
    teamHalved: false,
    dedup: 'name',
    scoring: 'option',
    namePlaceholder: '如：《曲园秋色》发表于大众日报（50 字以内）',
    options: [
      { key: 'national-media', label: '国家级报纸、新闻网站', points: 4 },
      { key: 'provincial-media', label: '省级报纸、新闻网站', points: 3 },
      { key: 'municipal-media', label: '地市级新闻报纸、网站', points: 2 },
      { key: 'school-media', label: '学校网站、公众号', points: 1 },
      { key: 'dept-media', label: '学工处和团委网站、公众号、智慧曲园', points: 0.8 },
      { key: 'college-media', label: '学院网站、公众号等', points: 0.5 },
    ],
    ruleNotes: [
      '同一文章发表在不同的报纸或网站，不累计加分，按最高级别计。',
      '作品名称限 50 字以内，备注限 100 字以内。',
    ],
  },
  {
    id: 'other',
    index: '09',
    name: '其他加分项',
    description: '学校、学院在本板块发布的活动，学生选择参与并填写参与情况，由主办单位审核。',
    cap: 5,
    teamHalved: false,
    dedup: 'none',
    scoring: 'custom',
    needsCustomPoints: true,
    namePlaceholder: '如：校长奖学金答辩会志愿者',
    options: [
      { key: 'school-activity', label: '学校发布的活动', points: 0 },
      { key: 'college-activity', label: '学院发布的活动', points: 0 },
    ],
    ruleNotes: [
      '需在活动结束一周内录入，等待主办单位审核。',
      '分值按学校或学院发布活动时设定的分值填写，单条不超过 5 分。',
    ],
  },
];

export const MODULE_MAP: Record<string, ModuleRule> = Object.fromEntries(
  MODULE_RULES.map(rule => [rule.id, rule]),
);

export const FULL_SCORE = MODULE_RULES.reduce((sum, rule) => sum + rule.cap, 0);

export const GRADE_SCALE = [
  { label: '优秀', threshold: 0.75 },
  { label: '良好', threshold: 0.6 },
  { label: '合格', threshold: 0.4 },
  { label: '待提升', threshold: 0 },
];
